import logging
import uuid
from datetime import UTC, date, datetime, timedelta

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import PlainTextResponse
from sqlalchemy import desc, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.dependencies.authentication import get_current_user
from app.db.dependencies import get_db_session
from app.models.ai_coach import ChatMessage, ChatSession
from app.models.body_weight import BodyWeight
from app.models.enums import ChatRole
from app.models.nutrition_log import NutritionLog
from app.models.user import User
from app.services.ai_coach import get_ai_coach_service

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/reports", tags=["Reports & Export"])

@router.get("/progress", response_class=PlainTextResponse)
async def export_progress_report(
    period: str = Query("weekly", description="weekly or monthly"),
    session: AsyncSession = Depends(get_db_session),
    current_user: User = Depends(get_current_user),
):
    """Generates a Markdown report of the user's progress and AI coach summaries."""
    today = date.today()
    if period == "weekly":
        start_date = today - timedelta(days=7)
    elif period == "monthly":
        start_date = today - timedelta(days=30)
    else:
        raise HTTPException(status_code=400, detail="Invalid period. Use 'weekly' or 'monthly'.")

    # Fetch Nutrition Logs
    nutrition_logs = (
        await session.execute(
            select(NutritionLog)
            .where(
                NutritionLog.user_id == current_user.id,
                NutritionLog.logged_date >= start_date,
                NutritionLog.logged_date <= today,
            )
            .order_by(NutritionLog.logged_date)
        )
    ).scalars().all()

    # Fetch Weight Logs
    weight_logs = (
        await session.execute(
            select(BodyWeight)
            .where(
                BodyWeight.user_id == current_user.id,
                BodyWeight.logged_date >= start_date,
                BodyWeight.logged_date <= today,
            )
            .order_by(BodyWeight.logged_date)
        )
    ).scalars().all()

    # Calculate Nutrition Stats
    daily_cals: dict[date, float] = {}
    daily_protein: dict[date, float] = {}
    for l in nutrition_logs:
        daily_cals[l.logged_date] = daily_cals.get(l.logged_date, 0) + float(l.calories_kcal)
        daily_protein[l.logged_date] = daily_protein.get(l.logged_date, 0) + float(l.protein_g)

    avg_cals = sum(daily_cals.values()) / max(1, len(daily_cals))
    avg_protein = sum(daily_protein.values()) / max(1, len(daily_protein))

    # Calculate Weight Trend
    weight_trend_str = "No weight data recorded."
    if weight_logs:
        start_wt = weight_logs[0]
        end_wt = weight_logs[-1]
        delta = float(end_wt.weight_kg) - float(start_wt.weight_kg)
        direction = "gained" if delta > 0 else "lost"
        weight_trend_str = f"Started at {start_wt.weight_kg}kg, ended at {end_wt.weight_kg}kg ({direction} {abs(delta):.1f}kg)."

    # Get AI Coach Summary
    ai_summary_str = "No AI insights available for this period."
    ai_service = get_ai_coach_service()

    recent_messages = (
        await session.execute(
            select(ChatMessage.content)
            .join(ChatSession, ChatMessage.session_id == ChatSession.id)
            .where(
                ChatSession.user_id == current_user.id,
                ChatMessage.role == ChatRole.ASSISTANT,
                ChatMessage.created_at >= datetime.combine(start_date, datetime.min.time()).replace(tzinfo=UTC)
            )
            .order_by(desc(ChatMessage.created_at))
            .limit(10)
        )
    ).scalars().all()

    if recent_messages:
        prompt = f"""
Summarize the user's recent AI coaching interactions into a brief, encouraging {period} summary.
Highlight key advice given and progress made. Keep it under 150 words.
Interactions:
{chr(10).join(recent_messages)}
"""
        try:
            ai_summary_str = await ai_service.chat(prompt, context=None)
        except Exception as e:
            logger.error(f"Failed to generate AI summary for report: {e}")
            ai_summary_str = "Failed to generate AI insights."

    # Build Markdown Report
    report = f"""# NutriMind AI - {period.capitalize()} Progress Report
**Date Range:** {start_date} to {today}

## Nutrition Overview
* **Average Daily Calories:** {avg_cals:.0f} kcal
* **Average Daily Protein:** {avg_protein:.1f} g
* **Days Logged:** {len(daily_cals)} days

## Weight Trend
* {weight_trend_str}

## AI Coach Insights
{ai_summary_str}

---
*Generated by NutriMind AI Coach on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S UTC')}*
"""

    return report


@router.get("/chat-export/{session_id}", response_class=PlainTextResponse)
async def export_chat_session(
    session_id: uuid.UUID,
    session: AsyncSession = Depends(get_db_session),
    current_user: User = Depends(get_current_user),
):
    """Exports a specific chat session as a Markdown/TXT file."""
    chat_session = (
        await session.execute(
            select(ChatSession)
            .where(
                ChatSession.id == session_id,
                ChatSession.user_id == current_user.id
            )
        )
    ).scalars().first()

    if not chat_session:
        raise HTTPException(status_code=404, detail="Session not found")

    messages = (
        await session.execute(
            select(ChatMessage)
            .where(ChatMessage.session_id == session_id)
            .order_by(ChatMessage.created_at)
        )
    ).scalars().all()

    lines = [f"# Chat Transcript: {chat_session.title}"]
    lines.append(f"**Date:** {chat_session.created_at.strftime('%Y-%m-%d')}")
    lines.append("")

    for msg in messages:
        role_label = "🧑 User" if msg.role == ChatRole.USER else "🤖 AI Coach"
        lines.append(f"### {role_label} ({msg.created_at.strftime('%H:%M:%S')})")
        lines.append(msg.content)
        lines.append("")

    return "\n".join(lines)
