"""Make nutrition profile core fields nullable

Revision ID: 0295723946b2
Revises: b9c8d7e6f5a0
Create Date: 2026-07-21 21:08:07.376901
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0295723946b2'
down_revision: Union[str, None] = 'b9c8d7e6f5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'cancelled', 'paused', name='goal_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('goals', 'progress_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('nutrition_profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('nutrition_profiles', 'biological_sex',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='biological_sex'),
               nullable=True)
    op.alter_column('nutrition_profiles', 'height_cm',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('nutrition_profiles', 'weight_kg',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('nutrition_profiles', 'activity_level',
               existing_type=postgresql.ENUM('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extra_active', name='activity_level'),
               nullable=True)
    op.alter_column('nutrition_profiles', 'goal',
               existing_type=postgresql.ENUM('lose_weight', 'maintain_weight', 'gain_weight', 'gain_muscle', name='nutrition_goal'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nutrition_profiles', 'goal',
               existing_type=postgresql.ENUM('lose_weight', 'maintain_weight', 'gain_weight', 'gain_muscle', name='nutrition_goal'),
               nullable=False)
    op.alter_column('nutrition_profiles', 'activity_level',
               existing_type=postgresql.ENUM('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extra_active', name='activity_level'),
               nullable=False)
    op.alter_column('nutrition_profiles', 'weight_kg',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('nutrition_profiles', 'height_cm',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('nutrition_profiles', 'biological_sex',
               existing_type=postgresql.ENUM('male', 'female', 'other', 'prefer_not_to_say', name='biological_sex'),
               nullable=False)
    op.alter_column('nutrition_profiles', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('goals', 'progress_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('goals', 'status',
               existing_type=postgresql.ENUM('active', 'completed', 'cancelled', 'paused', name='goal_status'),
               server_default=sa.text("'active'::goal_status"),
               existing_nullable=False)
    # ### end Alembic commands ###
