"""Add AIUserMemory and ChatMessage feedback

Revision ID: 407d1baba005
Revises: ff55163f8976
Create Date: 2026-07-22 19:35:41.882349
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '407d1baba005'
down_revision: Union[str, None] = 'ff55163f8976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_user_memories',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_user_memories_user_id'), 'ai_user_memories', ['user_id'], unique=False)
    op.add_column('chat_messages', sa.Column('is_helpful', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('is_not_helpful', sa.Boolean(), nullable=True))
    op.add_column('chat_messages', sa.Column('was_regenerated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chat_messages', sa.Column('was_copied', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'was_copied')
    op.drop_column('chat_messages', 'was_regenerated')
    op.drop_column('chat_messages', 'is_not_helpful')
    op.drop_column('chat_messages', 'is_helpful')
    op.drop_index(op.f('ix_ai_user_memories_user_id'), table_name='ai_user_memories')
    op.drop_table('ai_user_memories')
    # ### end Alembic commands ###
