"""Add category and recurrence to tasks

Revision ID: 9d331b5a060d
Revises: 407d1baba005
Create Date: 2026-07-28 01:52:55.608744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d331b5a060d'
down_revision: Union[str, None] = '407d1baba005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    task_category_enum = sa.Enum('daily_habit', 'exercise', 'water', 'sleep', 'medication', 'appointment', 'custom', name='task_category')
    task_category_enum.create(op.get_bind(), checkfirst=True)
    task_recurrence_enum = sa.Enum('none', 'daily', 'weekly', 'monthly', 'weekdays', 'weekends', name='task_recurrence')
    task_recurrence_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('tasks', sa.Column('category', task_category_enum, server_default='custom', nullable=False))
    op.add_column('tasks', sa.Column('recurrence', task_recurrence_enum, server_default='none', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'recurrence')
    op.drop_column('tasks', 'category')
    sa.Enum(name='task_recurrence').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_category').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
