"""Add phase 2 ai coach fields

Revision ID: ff55163f8976
Revises: f1a2b3c4d5e6
Create Date: 2026-07-22 19:20:03.809496
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ff55163f8976'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_trackers', sa.Column('meal_plans_used', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ai_usage_trackers', sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('ai_usage_trackers', 'messages_used',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('ai_usage_trackers', 'images_used',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.drop_column('ai_usage_trackers', 'plans_used')
    op.add_column('chat_messages', sa.Column('model_used', sa.String(length=50), nullable=True))
    op.add_column('chat_sessions', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chat_sessions', sa.Column('archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'archived')
    op.drop_column('chat_sessions', 'pinned')
    op.drop_column('chat_messages', 'model_used')
    op.add_column('ai_usage_trackers', sa.Column('plans_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('ai_usage_trackers', 'images_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_usage_trackers', 'messages_used',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('ai_usage_trackers', 'tokens_used')
    op.drop_column('ai_usage_trackers', 'meal_plans_used')
    # ### end Alembic commands ###
